server:
  port: 9091
  servlet:
    context-path: /
    session:
      timeout: 300

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: key01322
      value01: '{cipher}AIBliC2dT0/5aMFd9oeCZyXcPLhmBijGueieOkhnj1U6wAe7esJaWJhBPc+MrZaB/X22UrLYel+BMufjIh1+IBFYCgbJolEH1XB9G6LlEFd9OgcUhQqVTVkbV1ygPqFXdA8I50xURXhM+S0AkyCGmuN7jrz4FxemyIAeOrKYjdYcK2T4+GsttvmnYjxrrAriJxaQ6eXAEJxyYYAqZcPOYczx'

feign:
  hystrix:
    enabled: true