server:
  port: 9091
  servlet:
    context-path: /
    session:
      timeout: 300

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: key01
      value01: '{cipher}df9f93b9f7ec1edb83fd75fe60d9b86e26550577dcbd2f309c9a23b4f4805cb3'

feign:
  hystrix:
    enabled: true