server:
  port: 9091
  servlet:
    context-path: /
    session:
      timeout: 300

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-order
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      key01: key01
      value01: '{cipher}AIBvvwc0UyAUyvGYb0DEggtsyvIybT0OaK2Fbt2/ViMWfEmEwSPiwRwp8028yUdqW2F7/lejXe19iovQ5jZlL7OdWL2MkS5jVatdPGo7NEhOStRPIlWT721uS52xa9cSQXXFJXiy76LQiqdQCZNgwP7Pv1KDVg0oQ4zX9XsVYCa/5pqD0H1ezxDYzC4IIWfVNt1Z72n8H4cOQnB9hpgye9B1'

feign:
  hystrix:
    enabled: true