server:
  port: 9192
  servlet:
    context-path: /
    session:
      timeout: 300

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-user

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true